HOLY SHIT
Non-integer operand for operator < at line 19, character 18
Non-integer operand for operator < at line 21, character 18
Invalid operands for < operator, at line 22, character 20
Non-integer operand for operator < at line 22, character 18
Non-integer operand for operator < at line 24, character 18
Non-integer operand for operator + at line 27, character 11
Non-integer operand for operator + at line 29, character 11
Non-integer operand for operator + at line 30, character 11
Non-integer operand for operator + at line 32, character 11
Non-integer operand for operator + at line 33, character 11
Non-integer operand for operator + at line 34, character 11
Non-integer operand for operator + at line 36, character 24
Non-integer operand for operator - at line 39, character 11
Non-integer operand for operator - at line 41, character 11
Non-integer operand for operator - at line 42, character 11
Non-integer operand for operator - at line 44, character 11
Non-integer operand for operator - at line 45, character 11
Non-integer operand for operator - at line 46, character 11
Non-integer operand for operator - at line 48, character 24
Non-integer operand for operator * at line 51, character 11
Non-integer operand for operator * at line 53, character 11
Non-integer operand for operator * at line 54, character 11
Non-integer operand for operator * at line 56, character 11
Non-integer operand for operator * at line 57, character 11
Non-integer operand for operator * at line 58, character 11
Non-integer operand for operator * at line 60, character 24
