
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 25 06:07:26 EST 2012
//----------------------------------------------------

package minijavac.tools;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LBRACKET = 16;
  public static final int INTEGER = 36;
  public static final int LPAREN = 12;
  public static final int SEMI = 4;
  public static final int PRINTLN = 29;
  public static final int MINUS = 10;
  public static final int STATIC = 20;
  public static final int RPAREN = 13;
  public static final int NOT = 6;
  public static final int AND = 7;
  public static final int LESSTHAN = 8;
  public static final int COMMA = 3;
  public static final int CLASS = 18;
  public static final int PLUS = 9;
  public static final int ASSIGN = 5;
  public static final int MAIN = 22;
  public static final int IF = 26;
  public static final int THIS = 31;
  public static final int DOT = 2;
  public static final int BOOLEAN = 35;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int RBRACKET = 17;
  public static final int NEW = 32;
  public static final int error = 1;
  public static final int LCURLY = 14;
  public static final int BOOLEANTYPE = 33;
  public static final int VOID = 21;
  public static final int RCURLY = 15;
  public static final int TIMES = 11;
  public static final int ELSE = 27;
  public static final int WHILE = 28;
  public static final int PUBLIC = 19;
  public static final int INTTYPE = 34;
  public static final int EXTENDS = 23;
  public static final int STRING = 24;
  public static final int LENGTH = 30;
  public static final int IDENTIFIER = 37;
}

