package minijavac;

public class VariableAttribute extends Attribute {
	private boolean temp;
	private String type;
	private int size; // this may only be relevant for arrays
	private Storage storage;

	public VariableAttribute(String identifier, int line, int col, String t, int s) {
		super(identifier, line, col);
		type = t;
		size = s;
		temp = false;
		storage = new Storage();
	}

	public VariableAttribute(String identifier, int line, int col, String t) {
		this(identifier, line, col, t, 0);
	}

	// Constructor for temp vars generated by compiler
	public VariableAttribute(String identifier, String t) {
		this(identifier, -1, -1, t);
		temp = true;
	}

	public String getType() {
		return type;
	}

	public boolean isTemp() {
		return temp;
	}

	public boolean isSameType(String otherType){
		return type.equalsIgnoreCase(otherType);
	}
	
	public int getSize() {
		return size;
	}

	public void setStorage(Storage store) {
		storage = store;
	}

	public Storage getStorage() {
		return storage;
	}
}
