
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 09 17:44:36 EST 2012
//----------------------------------------------------

package tools;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PERIOD = 39;
  public static final int LPAREN = 33;
  public static final int INT = 3;
  public static final int PRINTLN = 24;
  public static final int OUT = 23;
  public static final int LESS = 12;
  public static final int MINUS = 10;
  public static final int RPAREN = 36;
  public static final int STATIC = 16;
  public static final int SEMICOLON = 37;
  public static final int NOT = 14;
  public static final int AND = 8;
  public static final int COMMA = 38;
  public static final int CLASS = 25;
  public static final int PLUS = 9;
  public static final int MAIN = 18;
  public static final int IF = 20;
  public static final int THIS = 30;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int SYSTEM = 22;
  public static final int RETURN = 26;
  public static final int EQUAL = 40;
  public static final int TRUE = 6;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int LSQBRACKET = 32;
  public static final int IDENT = 2;
  public static final int VOID = 17;
  public static final int TIMES = 11;
  public static final int LBRACE = 31;
  public static final int ELSE = 28;
  public static final int WHILE = 21;
  public static final int PUBLIC = 15;
  public static final int RBRACE = 34;
  public static final int EXTENDS = 19;
  public static final int RSQBRACKET = 35;
  public static final int STRING = 5;
  public static final int FALSE = 7;
  public static final int INT_LIT = 13;
  public static final int LENGTH = 29;
}

